version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9.7

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

  gcr-build-and-push:
    docker:
      - image: google/cloud-sdk:239.0.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Initialize gcloud CLI to connect to Google Cloud
          command: |
            # Store service account
            echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/gcloud-service-key.json
            # Initialize gcloud CLI
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
            gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE

      - run:
          name: Build image
          command: |
            docker build -t $DOCKER_IMAGE_NAME:$CIRCLE_SHA1 -f Dockerfile .

      - run:
          name: Push image
          command: |
            gcloud --quiet auth configure-docker
            docker push $DOCKER_IMAGE_NAME:$CIRCLE_SHA1

  gke-deploy:
    docker:
      - image: google/cloud-sdk:239.0.0
    steps:
      - run:
          name: Initialize gcloud CLI to connect to Google Cloud
          command: |

            # Store service account
            echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/gcloud-service-key.json

            # Initialize gcloud CLI
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
            gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
      - run:
          name: Install kubectl if missing
          command: |
            which kubectl || gcloud components install kubectl --quiet
      - run:
          name: Update k8s deployment image
          command: |
            # Get cluster credentials
            gcloud container clusters get-credentials ${GKE_CLUSTER}
            # Update deployment image
            kubectl --namespace ${K8S_NAMESPACE} \
              set image deployment ${K8S_DEPLOYMENT} \
              ${K8S_CONTAINER}=$DOCKER_IMAGE_NAME:$CIRCLE_SHA1

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build

      - gcr-build-and-push:
          context: kubone
          requires:
            - build

      - gke-deploy:
          context: kubone
          filters:
            branches:
              only:
                - master
          requires:
            - gcr-build-and-push
